import {
  faBath,
  faCar,
  faSnowflake,
  faTv,
  faUtensils,
  faWifi,
  faDollarSign,
  faEarthAmericas,
  faMugHot,
  faMagnifyingGlass,
  faBars,
  faCircleUser,
  faCloudArrowUp,
  faTrashCan,
  faStar,
  faHouseFlag,
  faHouseLock,
  faIdCard,
  faPlus,
  faImage,
  faImages,
  faArrowAltCircleLeft,
  faArrowUpFromBracket,
  faLocationDot,
  faChevronLeft,
  faChevronRight,
} from "@fortawesome/free-solid-svg-icons";
import { faCalendar, faHeart } from "@fortawesome/free-regular-svg-icons";

export const ICONS = Object.freeze({
  BATH: faBath,
  CAR: faCar,
  SNOWFLAKE: faSnowflake,
  TV: faTv,
  UTENSILS: faUtensils,
  WIFI: faWifi,
  DOLLAR: faDollarSign,
  EARTH: faEarthAmericas,
  LOGO: faMugHot,
  SEARCH: faMagnifyingGlass,
  BARS: faBars,
  USER: faCircleUser,
  UPLOAD: faCloudArrowUp,
  DELETE: faTrashCan,
  ADD: faPlus,
  STAR: faStar,
  PROFILE: faIdCard,
  BOOKINGS: faHouseFlag,
  ACCOMMODATIONS: faHouseLock,
  DATE: faCalendar,
  IMAGE: faImage,
  IMAGES: faImages,
  EXIT: faArrowAltCircleLeft,
  SHARE: faArrowUpFromBracket,
  LIKE: faHeart,
  LOCATION: faLocationDot,
  LEFT_ARROW: faChevronLeft,
  RIGHT_ARROW: faChevronRight,
});
